class Autogenerated {
  String? trackingId;
  String? customerName;
  String? customerPhone;
  String? customerAddress;
  int? collect;

  Autogenerated(
      {this.trackingId,
        this.customerName,
        this.customerPhone,
        this.customerAddress,
        this.collect});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    trackingId = json['tracking_id'];
    customerName = json['customer_name'];
    customerPhone = json['customer_phone'];
    customerAddress = json['customer_address'];
    collect = json['collect'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['tracking_id'] = this.trackingId;
    data['customer_name'] = this.customerName;
    data['customer_phone'] = this.customerPhone;
    data['customer_address'] = this.customerAddress;
    data['collect'] = this.collect;
    return data;
  }
}