name: amvines_rider_new
version: 1.0.0+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.0.3
  animated_splash_screen: ^1.3.0
  
  flutter: 
    sdk: flutter
  http: ^0.13.5
  google_fonts: ^4.0.4
  shared_preferences: ^2.0.13
  lottie: ^1.4.1
  internet_connection_checker: ^0.0.1+4
  image_picker: ^0.8.5+3
  signature: ^5.2.1
  path_provider: ^2.0.11
  change_app_package_name: ^1.1.0

  url_launcher: ^6.1.11
  intl: ^0.18.0
  pin_code_fields: ^7.4.0
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

dependency_overrides:
  path_provider: ^2.0.11

flutter: 
  uses-material-design: true

  assets:
  - assets/
  - assets/png/
  - assets/lottie/

  # example:
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300